from __future__ import annotations

from src.models.schemas import RiskReport, Severity

SEVERITY_EMOJI = {
    "CRITICAL": "\U0001f534",
    "HIGH": "\U0001f7e0",
    "MEDIUM": "\U0001f7e1",
    "LOW": "\U0001f7e2",
    "INFO": "ℹ️",
}

DECISION_EMOJI = {
    "BLOCK": "❌",
    "REVIEW": "⚠️",
    "APPROVE": "✅",
}

CHANGE_EMOJI = {
    "CREATE": "\U0001f7e2",
    "MODIFY": "\U0001f7e1",
    "DELETE": "\U0001f534",
}


def _sev(val: str) -> str:
    return f"{SEVERITY_EMOJI.get(val, '')} {val}"


def _dec(val: str) -> str:
    return f"{DECISION_EMOJI.get(val, '')} {val}"


def _ct(val: str) -> str:
    return f"{CHANGE_EMOJI.get(val, '')} {val}"


def generate_markdown(report: RiskReport) -> str:
    rl = report.risk_level.value if hasattr(report.risk_level, "value") else report.risk_level
    dec = report.decision.value if hasattr(report.decision, "value") else report.decision

    lines: list[str] = []

    lines.append("## \U0001f512 Infrastructure Change Risk Report")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(f"| **Change ID** | `{report.change_id}` |")
    lines.append(f"| **Risk Level** | {_sev(rl)} |")
    lines.append(f"| **Risk Score** | **{report.risk_score}**/100 |")
    lines.append(f"| **Decision** | {_dec(dec)} |")
    lines.append(f"| **Environment** | {report.evidence.environment} |")
    lines.append(f"| **Timestamp** | {report.timestamp[:19]} |")
    lines.append("")

    if report.evidence.changes:
        lines.append(f"### Resource Changes ({len(report.evidence.changes)})")
        lines.append("")
        lines.append("| Resource | Type | Change |")
        lines.append("|----------|------|--------|")
        for ch in report.evidence.changes:
            ct = ch.change_type.value if hasattr(ch.change_type, "value") else ch.change_type
            lines.append(f"| `{ch.resource_id}` | `{ch.resource_type}` | {_ct(ct)} |")
        lines.append("")

    if report.evidence.findings:
        lines.append(f"### Findings ({len(report.evidence.findings)})")
        lines.append("")
        lines.append("| Rule | Severity | Resource | Finding | Compliance |")
        lines.append("|------|----------|----------|---------|------------|")
        for f in report.evidence.findings:
            sev = f.severity.value if hasattr(f.severity, "value") else f.severity
            compliance_str = ", ".join(f.compliance) if f.compliance else "—"
            finding_text = f.finding.replace("|", "\\|")
            lines.append(f"| `{f.rule_id}` | {_sev(sev)} | `{f.resource}` | {finding_text} | {compliance_str} |")
        lines.append("")

    ai = report.ai_analysis
    if ai.explanation:
        lines.append("### AI Analysis")
        lines.append("")
        lines.append(f"**Explanation:** {ai.explanation}")
        lines.append("")
        if ai.blast_radius:
            lines.append(f"**Blast Radius:** {ai.blast_radius}")
            lines.append("")
        if ai.operational_impact:
            lines.append(f"**Operational Impact:** {ai.operational_impact}")
            lines.append("")

        has_facts = ai.facts and len(ai.facts) > 0
        has_inferences = ai.inferences and len(ai.inferences) > 0
        if has_facts or has_inferences:
            lines.append("<details>")
            lines.append("<summary>Facts & Inferences</summary>")
            lines.append("")
            if has_facts:
                lines.append("**Facts (Verified):**")
                for fact in ai.facts:
                    lines.append(f"- {fact}")
                lines.append("")
            if has_inferences:
                lines.append("**Inferences (AI-Derived):**")
                for inf in ai.inferences:
                    lines.append(f"- {inf}")
                lines.append("")
            lines.append("</details>")
            lines.append("")

    if ai.remediation:
        lines.append("### Remediation")
        lines.append("")
        lines.append(ai.remediation)
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [Production Change Risk Analyzer](https://github.com/vellankikoti/production-change-risk-analyzer)*")
    lines.append("")

    return "\n".join(lines)


def write_markdown(report: RiskReport, path: str) -> None:
    md = generate_markdown(report)
    with open(path, "w") as f:
        f.write(md)
